#!/bin/sh

msg() {
  # bold
  printf "\033[1m=> %s\033[m\n" "$@"
}

msg_pass() {
  # bold/green
  printf "\033[1m\033[32m %s: passed \033[m\n" "$@"
}

msg_fail() {
  # bold/red
  printf "\033[1m\033[31m %s\033[m\n" "$@"
}
