#!/bin/sh

msg() {
  # bold
  printf "\033[1m=> %s\033[m\n" "$@"
}

msg_res() {
  # bold
  printf "\033[1m=> %s\033[m\n" "getting results"
}

msg_run() {
  printf "running: %s...\n" "$@"
}

  # bold/green
test_pass() {
  varn=$1
  desc=$2
  res=$3
  eval value="\$${varn}"
  printf "\033[1m\033[32m   %s=%s %s '%s': passed \033[m\n"  "$varn" "$value"  "$desc" "$res"
}

msg_pass() {
  # bold/green
  printf "\033[1m\033[32m   %s: passed \033[m\n" "$@"
}

test_fail() {
  # bold/red
  printf "\033[1m\033[31m   %s\033[m\n" "$@" >&2
}

msg_fail() {
  # bold/red
  printf "\033[1m\033[31m   %s\033[m\n" "$@" >&2
}
