#!/bin/sh

set -m
##!/home/blank/dev/simpsh/simpsh
# vim: set filetype=sh:

sleep 8 &
sleep 8 &
sleep 8 &
sleep 8 &
bg %1
jobs

# ls
#
# false &&
# echo true ||
# echo false
#
# alias ec='echo test'
# ec
#
# PATH=$PATH:/home/blank/dev/simpsh/simpsh
#
# echo $PATH
